apiVersion: v1
kind: ServiceAccount
metadata:
  name: nccl-preflight-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nccl-preflight-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nccl-preflight-binding
subjects:
- kind: ServiceAccount
  name: nccl-preflight-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: nccl-preflight-role
  apiGroup: rbac.authorization.k8s.io