image:
  repository: 13.0.1-devel-ubuntu24.04-nccl2.29.2-1-2276a5e
  tag: 13.0.1-devel-ubuntu24.04-nccl2.29.2-1-2276a5e
  pullPolicy: IfNotPresent

expected:
  minBandwidthGBps: 350   # Adjust depending on GPU type
  minMessageSize: "128M"
  maxMessageSize: "1G"

shmSize: "2Gi"

nodeSelector:
  nvidia.com/gpu.count: "8"