apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: preflight-tests-workspace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-mounted-fs-path-sc