apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-status.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cluster-status.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cluster-status.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          command: ["/bin/sh"]
          args:
            - -c
            - |
              pip install fastapi uvicorn && \
              uvicorn main:app --host 0.0.0.0 --port 8000
          env:
            - name: DATA_FILE
              value: "{{ .Values.app.dataFile }}"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: app-code
              mountPath: /app
            - name: pvc-data
              mountPath: {{ .Values.pvc.mountPath }}
              readOnly: true

      volumes:
        - name: app-code
          configMap:
            name: {{ include "cluster-status.fullname" . }}-app

        - name: pvc-data
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.existingClaim }}